name: build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install nextflow
        uses: nf-core/setup-nextflow@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install .[dev,test]
          python -c 'from sinclair.src.util import chmod_bins_exec; chmod_bins_exec()'
      - name: Check out-of-the-box CLI script
        run: |
          bash bin/sinclair --help
      - name: Check CLI basics
        run: |
          which sinclair
          sinclair --version
          sinclair --citation
      - name: Stub run
        run: |
          mkdir tmp && cd tmp
          sinclair init
          sinclair run \
            -stub \
            -profile docker,ci_stub \
            -entry GEX \
            --input ../test_dir/gex_samplesheet.csv \
            --contrast ../assets/contrast_manifest.csv
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        if: always() # run even if previous steps fail
        with:
          name: nextflow-log
          path: .nextflow.log
  build-status: # https://github.com/orgs/community/discussions/4324#discussioncomment-3477871
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
      - name: Successful build
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failing build
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
